[tool.poetry]
name = "odd-collector-aws"
version = "0.1.1"
description = "ODD Collector for AWS"
license = "Apache-2.0"
authors = ["Open Data Discovery <pypi@opendatadiscovery.org>"]
homepage = "https://github.com/opendatadiscovery/odd-collector-aws"
repository = "https://github.com/opendatadiscovery/odd-collector-aws"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0.1"
python-dotenv = "^0.19.0"
gunicorn = "^20.1.0"
boto3 = "^1.18.44"
pyhumps = "^3.0.2"
more-itertools = "^8.10.0"
lark-parser = "^0.12.0"
APScheduler = "^3.8.1"
humps = "^0.2.2"
oddrn-generator = "^0.1.10"
odd-models = "^1.0.14"
pydantic = "^1.8.2"
black = "^21.12b0"
aiohttp = "^3.8.1"
pyarrow = "^6.0.1"
numpy = "^1.22.1"
odd-collector-sdk = "^0.1.3"


[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.5"

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
