[tool.poetry]
name = "odd-collector-aws"
version = "0.1.2"
description = "ODD Collector for AWS"
license = "Apache-2.0"
authors = ["Open Data Discovery <pypi@opendatadiscovery.org>"]
homepage = "https://github.com/opendatadiscovery/odd-collector-aws"
repository = "https://github.com/opendatadiscovery/odd-collector-aws"

[tool.poetry.dependencies]
python = "^3.9"
oddrn-generator = "0.1.45"
python-dotenv = "0.19.0"
boto3 = "1.18.44"
lark-parser = "0.12.0"
pyhumps = "3.0.2"
pyarrow = "6.0.1"
humps = "0.2.2"
flatdict = "4.0.1"
more-itertools = "8.10.0"
odd-collector-sdk = "0.3.1"
funcy = "1.17"

[tool.black]
target-version = ['py39']
preview = true


[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.5"

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
